### ISSUE TITLE
search function return "nothing"

### ISSUE THREAD

**Issue by Error-Cezar** [DevSnowflake/node-xvdl#1]
so I tried to used the search function but I get `{ videos: [] }` everytime I search something

I tried with this `XVDL.search(url)
    .then(info => console.log(info))
    .catch(e => console.error(e));`

**Comment by twlite** [comment]
Looks like xvideos updated their site. I will look into this when I have time

**Comment by Error-Cezar** [comment]
alright

**Comment by twlite** [comment]
fixed in v2
